config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get "pages/home"
  root to: 'pages#home'
  get '/search', to: 'pages#search'
  post '/search', to: 'pages#search', as: 'results'
  get '/monprojet', to: "pages#monprojet"
  get '/themes/:title', to: "themes#show", as: :theme
  resources :themes, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :theme
  belongs_to :link

  validates_uniqueness_of :link_id, :scope => [:theme_id]
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_many :tags

  validates :title, presence: true, uniqueness: true


end

app/models/link.rb
class Link < ApplicationRecord
  has_many :tags, dependent: :destroy
  has_many :keywords, through: :tags
  has_many :categories, dependent: :destroy
  has_many :themes, through: :categories

  validates :format, presence: true, inclusion: { in: %w(livre pdf article blog association guide) }
  validates :title, presence: true
  validates :publication, presence: true
  validates :language, presence: true
  validates :description, presence: true
  validates :note, presence: true
  validates :url, presence: true

  # searchkick word_middle: [:format, :title, :publication, :description, :note]
  # searchkick match: :word_middle
  # searchkick word_start: [:title, :author, :genre]
  searchkick searchable: [ :keywords]

  def search_data
    {
    # format: format,
    # publication: publication
    }
    attributes.merge(
      keywords: keywords.map(&:title)
    )
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :link
  belongs_to :keyword

  validates_uniqueness_of :link_id, :scope => [:keyword_id]
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :categories

  validates :title, presence: true, inclusion: { in: %w(s'informer gerer gérer vivre ressources recherche) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :theme_redirection

private
 def theme_redirection
    redirect_to theme_path(params[:query]) if %w(s'informer gerer vivre ressources recherche).include?(params[:query])
    redirect_to theme_path("gerer") if params[:query] == "gérer"
 end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # @search = Link.search(params.fetch(:query, "*"))
    @format = ["livre", "pdf", "article", "blog", "association"].sort
    @links = Link.all

    if params[:format] == "all"
      @link_search = Link.search params[:query], fields: [ :keywords ], where: {keywords: params[:query]}
    else
      @link_search = Link.search params[:query], fields: [ :keywords ], where: {format: params[:format]}
    end
    # @link_search = Link.search params[:query], fields: [ :keywords ], where: {keywords: params[:query]}

    @themes = Theme.all

    @keywords = Keyword.all
  end

  def search
    # @search = Link.search(params.fetch(:query, "*"))
    # @link_search = Link.search params[:query], fields: [ :keywords ]

    # if params[:query].present? && params[:format].present?
      # @link_search = Link.search params[:query], fields: [ :keywords ], where: {format: params[:format]}
      # @link_search = Link.search params[:query], fields: [ :keywords ], where: {keywords: params[:query]}
    # else
    #   redirect_to request.referrer, flash: { error: "Choisissez un format ET un mot clé !" }
    # end

    if params[:format] == "all"
      @link_search = Link.search params[:query], fields: [ :keywords ], where: {keywords: params[:query]}
    else
      @link_search = Link.search params[:query], fields: [ :keywords ], where: {format: params[:format]}
    end

    @themes = Theme.all

    @links = Link.all
    @links_theme = Theme.where(title: params[:query])

    @format = ["livre", "pdf", "article", "blog", "association"].sort

    @keywords = Keyword.all
  end

  def monprojet
    @themes = Theme.all
    @format = ["livre", "pdf", "article", "blog", "association"].sort
    @keywords = Keyword.all
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def show
    @themes = Theme.all
    @theme = Theme.find_by_title(params[:title])

    @livre_formatted_links = Link.where(format: "livre").joins(:themes).where(themes: { title: @theme.title })
    @article_formatted_links = Link.where(format: "article").joins(:categories).joins(:themes).where(themes: { title: @theme.title })
    @information_formatted_links = Link.where(format: "information").joins(:categories).joins(:themes).where(themes: { title: @theme.title })
    @association_formatted_links = Link.where(format: "association").joins(:themes).where(themes: { title: @theme.title })
    @guide_formatted_links = Link.where(format: "guide").joins(:themes).where(themes: { title: @theme.title })

    @keywords = Keyword.all

    @ressources = Link.joins(:themes).where(themes: { title: "ressources" })

    @format = %w(livre pdf article blog association guide)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<!--     <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Le Cancer du Sein | COMPRENDRE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <% if current_page?(root_path) %>
      <%= render 'shared/navbarhome' %>
    <% else %>
      <%= render 'shared/navbar' %>
    <% end %>

    <%= yield %>

    <%= render 'shared/footer' %>

    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper-pink">
  <div class="container">
    <div class="centered-container">
      <div class="catchphrase-big text-center">
        <h3>Et si rechercher sa maladie sur Internet n'était plus un tabou ?</h3>
      </div>
      <div class="searchbar">
        <%= form_tag results_path, method: :get do %>
         <!--  <div class="select"> -->
            <%#= select_tag :format,
              options_for_select(@format, params[:format]),
              class: "dropdown-home",
              prompt: "Un format ?"
            %>
          <!-- </div> -->
          <!-- <div class="select"> -->
            <%#= collection_select :query, :query, Keyword.all, :title, :title, prompt: "Un mot-clé ?" %>
          <!-- </div> -->
          <%#= text_field_tag :query,
            params[:query],
            class: "searchbar-big",
            placeholder: "Un mot-clé ?"
          %>
          <div class="select">
            <%= select_tag :query,
            options_from_collection_for_select(@keywords, :title,:title , params[:query]),
            class: "dropdown-keyword-home",
            prompt: "Je veux me renseigner sur ..."
            %>
          </div>
          <%= hidden_field_tag(:format, 'all') %>
          <%= button_tag(type: "submit", class: "btn btn-default search-button") do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>

        <% flash.each do |key, value| %>
          <div class="alert alert-warning"><%= value %></div>
        <% end %>
<!--         <div class="tips text-center">
          <p>Exemples : radiothérapie, douleurs, perruques, HER2+ ...</p>
        </div> -->
      </div>
    </div>
  </div>
</div>
<div class="wrapper-white-top">
  <h2>Liens récemment ajoutées</h2>
  <div class="results-total-last">
    <% @links.last(5).each do |l| %>
      <div class="results-last">
        <span class="results-last-format"><%= l.format %></span>
        <h5>
          <%= link_to l.url do  %>
            <%= l.title %> de <%= l.publication %>
          <% end %>
        </h5>
        <p><%= l.note %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/monhistoire.html.erb
<h1>Hello!</h1>

app/views/pages/monprojet.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-warning"><%= value %></div>
<% end %>

<div class="wrapper-white-flex">
  <div class="title">
    <h1>LE PROJET</h1>
  </div>
  <div class="paragraphs text-center">
    <h5>Peut-être votre médecin vous l’a-t-il dit ? Mais surtout, « ne cherchez pas sur Internet ». Internet est un trésor, certes, mais les témoignages fatalistes et les informations peu qualitatives y grouillent. Y trouvez les articles, les conseils « pépites » demandent un peu de temps et de patience. Alors, par souci pour votre santé et pour votre moral, vos médecins vous demandent parfois de ne pas aller chercher sur Internet. Oui, vous avez un cancer, la nouvelle est déjà terrible, n’est-il peut-être pas nécessaire de lire sur des forums que la mort vous guette.

    <br>
    <br>

    Mon projet a pour but de regrouper les pépites d’Internet sur la maladie (les blogs, les sites Internet des associations, les articles de qualité, les nouvelles recherches et avancées sur la maladie, les livres …). Faire des recherches sur sa maladie ne devrait pas être une aventure à travers l’Amazonie. J’espère que cette expérience pour vous sera aussi agréable qu’une balade sur la Seine un beau jour de printemps.
    </h5>
  </div>
</div>

<div class="banner">
  <%= image_tag asset_path("search-clcds-illustration.png"), class: "banner-illustration" %>
</div>

<div class="wrapper-white-flex">
  <div class="title">
    <h1>MON HISTOIRE</h1>
  </div>
  <div class="paragraphs text-center">
    <h5>La nouvelle est tombée un gris matin de mars 2017. A 26 ans, sans aucun antécédent dans la famille, je venais d’être diagnostiquée d’un cancer du sein, de type « triple négatif ». Comme la plupart des cancers chez les jeunes, sa progression est rapide, le grade est élevé (III).

    <br>
    <br>

    Aujourd’hui, je vais bien. Ma rémission a commencé un an après avec un changement de carrière. D’analyste financière en Venture Capital, j’ai entamé une formation en développement web. Avec ces nouvelles compétences, je me suis lancée dans une quête thérapeutique : ce premier projet.
    </h5>
  </div>
</div>

app/views/pages/search.html.erb
<div class="wrapper-white">

  <% flash.each do |key, value| %>
    <div class="alert alert-warning"><%= value %></div>
  <% end %>

  <div class="results-count">
    <h2><%= pluralize @link_search.total_count, "résultat" %> pour "<%= params[:query] %>"</h2>
  </div>

  <%#= params[:query] %>


  <div class="filtering-form">
    <div class="filter-button">
      <%= form_tag results_path, method: :get do %>
        <%= hidden_field_tag(:query, params[:query]) %>
        <%= button_tag(type: "submit", name: "format", value: "article", class: "btn btn-default search-button") do %>
          <h4>Article</h4>
        <% end %>
      <% end %>
    </div>

    <div class="filter-button">
      <%= form_tag results_path, method: :get do %>
        <%= hidden_field_tag(:query, params[:query]) %>
        <%= button_tag(type: "submit", name: "format", value: "all", class: "btn btn-default search-button") do %>
          <h4>All</h4>
        <% end %>
      <% end %>
    </div>

    <div class="filter-button">
      <%= form_tag results_path, method: :get do %>
        <%= hidden_field_tag(:query, params[:query]) %>
        <%= button_tag(type: "submit", name: "format", value: "livre", class: "btn btn-default search-button") do %>
          <h4>Livre</h4>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="results-list">
    <div class="results-list-head">
      <% @themes.each do |t| %>
        <% if @link_search.results.count { |ls| ls.themes.include?(t) } != 0 %>
          <div class="results-theme">
            <h6>Dans la catégorie "<%= t.title %>" (<%= pluralize @link_search.results.count { |ls| ls.themes.include?(t) }, "résultat" %>)</h6>
          </div>
          <% @link_search.results.sort_by(&:"created_at").each do |ls| %>
            <% ls.themes.each do |lst| %>
              <% if t == lst %>
                <div class="results-article">
                  <div class="results-article-title">
                    <h6><%= ls.format %></h6> <br>
                    <h6><%= ls.publication %>
                      <% unless ls.date.nil? %>
                        , <%= ls.date %>
                      <% end %>
                    </h6>
                    <br>
                    <div class="marg-title">
                      <%= link_to ls.url, target: "_blank", class: "results-article-link" do %>
                        <h1><%= ls.title %></h1>
                      <% end %>
                    </div>
                  </div>
                  <p><%= ls.description %></p>
                  <p class="results-article-note">Avis de l'équipe : <%= ls.note %></p>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg extra-pad">
  <div class="navbar-left">
    <%= link_to root_path do %>
      <%= image_tag asset_path("logo.png"), class: "logo-navbar" %>
    <% end %>
  </div>

  <div class="navbar-over-right">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <div class="navbar-right collapse navbar-collapse nb-rgt-coll-desktop" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% @themes.order('created_at ASC').each do |t| %>
          <div class="item-navbar-right-pink">
            <%= link_to theme_path(t.title) do %>
              <h6><%= t.title %></h6>
            <% end %>
          </div>
        <% end %>
        <div class="item-navbar-right-grey">
          <%= link_to monprojet_path do %>
            <h6>mon projet</h6>
          <% end %>
        </div>
      </div>
    </div>
    <div class="item-navbar-right-black">
      <%= form_tag results_path, method: :get do %>
        <%= hidden_field_tag(:format, 'all') %>
<!--         <div class="select-navbar">
          <%#= select_tag :format,
            options_for_select(@format, params[:format]),
            class: "dropdown-navbar",
            prompt: "Un format?"
          %>
        </div> -->
        <div class="select-navbar">
          <%#= collection_select :query, :query, Keyword.all, :title, :title, prompt: "Un mot-clé ?" %>
          <%= select_tag :query,
          options_from_collection_for_select(@keywords, :title,:title , params[:query]),
          class: "dropdown-navbar-2",
          prompt: "Chercher un autre thème"
          %>
        </div>
        <%#= text_field_tag :query,
          params[:query],
          autocomplete: "off",
          class: "searchbar-medium",
          placeholder: "Un mot-clé ?"
        %>
        <%= button_tag(type: "submit", class: "btn btn-default search-button-submit transparent-background") do %>
          <i class="fas fa-search"></i>
        <% end %>

        <%= button_tag(type: "button", class: "btn btn-default search-button-js transparent-background") do %>
          <h6>chercher</h6>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

<div class="search-nav">
  <%= form_tag results_path, method: :get do %>
    <%= hidden_field_tag(:format, 'all') %>
<!--     <div class="select">
      <%#= select_tag :format,
        options_for_select(@format, params[:format]),
        class: "dropdown-home",
        prompt: "Un format ?"
      %>
    </div> -->
    <div class="select">
      <%= select_tag :query,
      options_from_collection_for_select(@keywords, :title,:title , params[:query]),
      class: "dropdown-keyword-home",
      prompt: "Un mot-clé ?"
      %>
    </div>
    <%#= text_field_tag :query,
      params[:query],
      autocomplete: "off",
      class: "searchbar-big",
      placeholder: "Rechercher un mot-clé"
    %>
    <%= button_tag(type: "submit", class: "btn btn-default search-button") do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>
<nav class="navbar-right collapse navbar-collapse nb-rgt-coll-mobile" id="navbarNavAltMarkup">
  <div class="navbar-nav">
    <% @themes.order('created_at ASC').each do |t| %>
      <div class="item-navbar-right-pink">
        <%= link_to theme_path(t.title) do %>
          <h6><%= t.title %></h6>
        <% end %>
      </div>
    <% end %>
    <div class="item-navbar-right-grey">
      <%= link_to monprojet_path do %>
        <h6>mon projet</h6>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_navbarhome.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="navbar-left">
    <%= link_to root_path do %>
      <%= image_tag asset_path("logo.png"), class: "logo-navbar" %>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars"></i>
  </button>
  <div class="navbar-right collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% @themes.order('created_at ASC').each do |t| %>
        <div class="item-navbar-right-pink">
          <%= link_to theme_path(t.title) do %>
            <h6><%= t.title %></h6>
          <% end %>
        </div>
      <% end %>
      <div class="item-navbar-right-grey">
        <%= link_to monprojet_path do %>
          <h6>mon projet</h6>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/themes/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-warning"><%= value %></div>
<% end %>

<div class="wrapper-white">
  <div class="results-count">
    <h2>Dans la catégorie "<%= @theme.title %>" (<%= pluralize @theme.categories.count, "résultat" %>)</h2>
  </div>
  <div class="results-list-head">
    <div class="results-list">

      <% if @article_formatted_links.count != 0 %>
        <div class="results-theme">
          <h6>Les articles (<%= pluralize @article_formatted_links.count, "résultat" %>)</h6>
        </div>
        <div id="accordion">
          <% @keywords.order('title ASC').each do |k| %>
            <% if @article_formatted_links.count { |ls| ls.keywords.include?(k) } != 0 %>
              <div class="card">
                <div class="card-header" id="heading-article<%= k.id %>">
                  <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-article<%= k.id %>" aria-expanded="true" aria-controls="collapse-article<%= k.id %>"><%= k.title %></button>
                  </h5>
                </div>
                <div id="collapse-article<%= k.id %>" class="collapse" aria-labelledby="heading-article<%= k.id %>" data-parent="#accordion">
                  <div class="card-body">
                    <% k.tags.each do |kt| %>
                      <% if kt.link.keywords.include?(k) && kt.link.themes.include?(@theme) %>
                        <div class="results-article">
                          <div class="results-article-title">
                            <h6><%= kt.link.publication %>
                              <% unless kt.link.date.nil? %>
                                , <%= kt.link.date %>
                              <% end %>
                            </h6>
                            <br>
                            <div class="marg-title">
                              <%= link_to kt.link.url, target: "_blank", class: "results-article-link" do %>
                                <h1><%= kt.link.title %></h1>
                              <% end %>
                            </div>
                          </div>
                          <p><%= kt.link.description %></p>
                          <p class="results-article-note">Avis de l'équipe : <%= kt.link.note %></p>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <% if @livre_formatted_links.count != 0 %>
        <div class="results-theme">
          <h6>Les livres (<%= pluralize @livre_formatted_links.count, "résultat" %>)</h6>
        </div>
        <% @livre_formatted_links.each do |l| %>
          <div class="results-article">
            <div class="results-article-title">
              <h6><%= l.publication %>
                <% unless l.date.nil? %>
                  , <%= l.date %>
                <% end %>
              </h6>
              <div class="marg-title">
                <%= link_to l.url, target: "_blank", class: "results-article-link" do %>
                  <h1><%= l.title %></h1>
                <% end %>
              </div>
            </div>
            <p><%= l.description %></p>
            <p class="results-article-note">Avis de l'équipe : <%= l.note %></p>
          </div>
        <% end %>
      <% end %>

      <% if @association_formatted_links.count != 0 %>
        <div class="results-theme">
          <h6>Les associations (<%= pluralize @association_formatted_links.count, "résultat" %>)</h6>
        </div>
        <div id="accordion">
          <% @keywords.order('title ASC').each do |k| %>
            <% if @association_formatted_links.count { |ls| ls.keywords.include?(k) } != 0 %>
              <div class="card">
                <div class="card-header" id="heading-association-<%= k.id %>">
                  <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-association-<%= k.id %>" aria-expanded="true" aria-controls="collapse-association-<%= k.id %>"><%= k.title %></button>
                  </h5>
                </div>
                <div id="collapse-association-<%= k.id %>" class="collapse" aria-labelledby="heading-association-<%= k.id %>" data-parent="#accordion">
                  <div class="card-body">
                    <% k.tags.each do |kt| %>
                      <% if kt.link.keywords.include?(k) && kt.link.themes.include?(@theme) %>
                        <div class="results-article">
                          <div class="results-article-title">
                            <%= link_to kt.link.url, target: "_blank", class: "results-article-link" do %>
                              <h4><%= kt.link.title %></h4>
                            <% end %>
                            <h6>/ publié par <%= kt.link.publication %>
                              <% unless kt.link.date.nil? %>
                                , <%= kt.link.date %></h6>
                              <% end %>
                          </div>
                          <p><%= kt.link.description %></p>
                          <p class="results-article-note">Avis de l'équipe : <%= kt.link.note %></p>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
</div>